name: CI Tests API

on:
  push:
    branches: [dev]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run pytest (no DB)
        run: |
          #PYTHONPATH=. pytest -m "not db" --cov=app --cov-report=term
          #PYTHONPATH=. pytest --ignore=tests/test_auth.py --cov=app --cov-report=term
          pytest tests/test_feature_builder.py \
                 tests/test_validation_errors.py \
                 tests/test_predict_api_errors.py \
                 tests/test_predict_pipeline.py
                 --cov=app
